# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fottchen blog
email: fottchen@163.com
description: > # this means to ignore newlines until "baseurl:"
  这是 <b><a href="http://weibo.com/bgconec">fottchen 陈文超 </a></b> 写字集思的地方，大环境太吵太急躁，无人知晓的小地方更能安静思考，如果你喜欢我的文字，欢迎时常来这里看看
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fottchen.com" # the base hostname & protocol for your site
github_username:  fottchen

# Build settings
markdown: kramdown
